# Generated by Django 4.2.1 on 2023-05-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='.', max_length=50),
            preserve_default=False,
        ),
    ]
