# Generated by Django 4.2.1 on 2023-05-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_zip_address_zip1_remove_product_membership_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_name',
        ),
    ]
